## numpy概览
- NumPy包的核心是 ndarray 对象。它封装了python原生的同数据类型的 n 维数组，为了保证其性能优良，其中有许多操作都是代码在本地进行编译后执行的。
- NumPy的主要对象是同构多维数组。它是一个元素表（通常是数字），所有类型都相同，由非负整数元组索引。在NumPy维度中称为 轴 。

## ndarray对象（核心）
- ndarray.ndim - 数组的轴（维度）的个数。在Python世界中，维度的数量被称为rank。
- ndarray.shape - 数组的维度。这是一个整数的元组，表示每个维度中数组的大小。对于有 n 行和 m 列的矩阵，shape 将是 (n,m)。因此，shape 元组的长度就是rank或维度的个数 ndim。
- ndarray.size - 数组元素的总数。这等于 shape 的元素的乘积。
- ndarray.dtype - 一个描述数组中元素类型的对象。可以使用标准的Python类型创建或指定dtype。另外NumPy提供它自己的类型。例如numpy.int32、numpy.int16和numpy.float64。
- ndarray.itemsize - 数组中每个元素的字节大小。例如，元素为 float64 类型的数组的 itemsize 为8（=64/8），而 complex32 类型的数组的 itemsize 为4（=32/8）。它等于 ndarray.dtype.itemsize 。
- ndarray.data - 该缓冲区包含数组的实际元素。通常，我们不需要使用此属性，因为我们将使用索引访问数组中的元素。

In [38]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)
print(type(a))

#改变dytpe
print(a.astype(float).dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>
float64


## 创建数组

In [11]:
# 通过python数组
a = np.array([2,3,4])
print(a)
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

# 序列里包含数组
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

# 创建时指定类型
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[2 3 4]
int32
float64
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [14]:
# 初始化创建zero，one；随机创建empty
print (np.zeros( (3,4) ))
print(np.ones( (2,3,4), dtype=np.int16 ))              
print (np.empty( (2,3) ))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [17]:
# arrange 创建
print(np.arange( 10, 30, 5 ))
print(np.arange( 0, 2, 0.3 ))

#对于小数点，用linspace创建
from numpy import pi
print(np.linspace( 0, 2, 9 ))

x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)
print(f)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01

# 打印数组

In [18]:
# print和reshape函数
a = np.arange(6)       
print(a)

b = np.arange(12).reshape(4,3)     
print(b)

c = np.arange(24).reshape(2,3,4)  
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
#读取数据
world_alchohol = np.genfromtxt("./../../data/world_alcohol.txt",delimiter=",",dtype=str,encoding="utf-8")
print(type(world_alchohol))
print(world_alchohol)

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


## 数学运算

In [27]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

c = a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [29]:
# 乘积和矩阵乘积@
A = np.array( [[1,1],
          [0,1]] )
B = np.array( [[2,0],
           [3,4]] )
print(A * B)   
print(A @ B)           
print(A.dot(B))    

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


## axis指定操作某条轴

In [ ]:
b = np.arange(12).reshape(3,4)
print(b.sum(axis=0)
print(b.min(axis=1))
print(b.cumsum(axis=1))                         # cumulative sum along each row

## 通函数
- 另见这些通函数
all
， any ， apply_along_axis ， argmax ， argmin ， argsort ， average ， bincount ， ceil ， clip ， conj ， corrcoef ， cov ， cross ， cumprod ， cumsum ， diff ， dot ， floor ， inner ， INV ， lexsort ， max ， maximum ， mean ， median ， min ， minimum ， nonzero ， outer ， prod ， re ， round ， sort ， std ， sum ， trace ， transpose ， var ， vdot ， vectorize ， where 

In [53]:
B = np.arange(3)
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1., 4.])
print(np.add(B, C))

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


## 索引、切片和迭代
- 一维的数组可以进行索引、切片和迭代操作的，就像 列表 和其他Python序列类型一样。

In [54]:
#取某个值
vector = np.array([5, 10, 15, 20])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
number_1 = vector[2]#15
number_2 = matrix[1,2]#30
print(number_1)
print(number_2)
#分割取多个值,和列表差不多
print(vector[0:3])#[ 5 10 15]
#取列或行
print(matrix[:,1])#[10 25 40]
print(matrix[1])#[20 25 30]
#取多行多列
print(matrix[:,0:2])#[[ 5 10] [20 25] [35 40]]
print(matrix[1:3,0:2])#[[20 25] [35 40]]

15
30
[ 5 10 15]
[10 25 40]
[20 25 30]
[[ 5 10]
 [20 25]
 [35 40]]
[[20 25]
 [35 40]]


In [55]:
#判断类型----数组里面的元素必须是同一类型的
numbers = np.array([1,2,3,4])
print(numbers)#int32
#判断类型
print(numbers.dtype)
#更改类型
numbers = np.array([1, 2, 3, 4.0])
print(numbers)#[1. 2. 3. 4.]
print(numbers.dtype)#float64
#改成str类型
#改变一个类型其他的都改变
numbers = np.array([1, 2, 3, '4'])
print(numbers)#['1' '2' '3' '4']

[1 2 3 4]
int32
[1. 2. 3. 4.]
float64
['1' '2' '3' '4']


In [56]:
import numpy
#判断矩阵是否含某个值
def Judge_bool():
    vector = numpy.array([5, 10, 15, 20])
    matrix = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
    print(matrix==25)
    # 用判断当作索引
    equal_to_ten = (vector==10)
    print(equal_to_ten)
    print(vector[equal_to_ten])
    #数组判断出值，可以输出一行或者一列
    second_column_25 = (matrix[:,1]==25)
    print(second_column_25)
    print(matrix[second_column_25,:])
Judge_bool()

[[False False False]
 [False  True False]
 [False False False]]
[False  True False False]
[10]
[False  True False]
[[20 25 30]]


In [57]:
#判断矩阵是否含某个值，或与操作
def Judeg_and_or(vector,matrix):
    enual_to_ten_and_five_1 = (vector==10)|(vector==5)
    enual_to_ten_and_five_2 = (vector == 10)&(vector == 5)
    print(enual_to_ten_and_five_1)
    print(enual_to_ten_and_five_2)
    #用取出来的索引，改变某些值
    vector[enual_to_ten_and_five_1]=50
    print(vector)
    #对二维
    second_column_25 = matrix[:,1]==25
    print(second_column_25)
    matrix[second_column_25,1] = 10
    print(matrix)
Judeg_and_or(vector,matrix)

[ True  True False False]
[False False False False]
[50 50 15 20]
[False  True False]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [58]:
#改变类型,求和，求极值
def change_type(matrix):
    vector = numpy.array(["1", "2", "3"])
    print(vector.dtype)
    vector=vector.astype(float)
    print(vector.dtype)
    print(vector)
    #计算函数
    print(vector.min())
    print(vector.sum())#axis=1按行求和
    matrix_1=matrix.sum(axis=1)#[ 30  75 120]
    matrix_2 = matrix.sum(axis=0)#按列求和[60 75 90]
    print(matrix_1)
    print(matrix_2)
change_type(matrix)

<U1
float64
[1. 2. 3.]
1.0
6.0
[ 30  60 120]
[60 60 90]


In [59]:
#分配行和列,常用函数
def column_row():
    print(numpy.arange(15))
    a = numpy.arange(15).reshape(3, 5)
    print(a)
    print(a.shape)
    print(a.ndim)#维度
    print(a.dtype.name)
    print(a.size)
    print(numpy.zeros((3, 4)))#初始化为0
    #arange
    print(numpy.arange(10,30,5))
    print(numpy.arange(12).reshape(4,3))
    #构造单位矩阵
    print(numpy.ones((2, 3, 4), dtype = numpy.int32))
    print(numpy.random.random((2, 3)))
    #引入π值
    from numpy import pi
    print(numpy.linspace(0, 2 * pi, 100))#0到2pi平均取100个值
column_row()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
15
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20 25]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[0.4769049  0.58368499 0.9625059 ]
 [0.71189724 0.24648024 0.46846439]]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.490658

In [60]:
#数组之间的数学运算
def math_array():
    a = numpy.array([20, 30, 40, 50])
    b = numpy.arange(4)
    c = a-b
    print(c)
    c=c-1
    print(c)
    print(b**2)
    print(a<35)
    print("----------")
    A = numpy.array([[1, 1],
                      [0,1]])
    B = numpy.array([[2, 0],
                      [3,4]])
    print(A*B)#*乘是对应位置相乘
    print(A.dot(B))#矩阵乘法
    print(numpy.dot(A, B))

    B= numpy.arange(3)
    print(numpy.exp(B))#e的幂次方
    print(numpy.sqrt(B))#每个数求平方
    #floor向下取整
    a = numpy.floor(10 * numpy.random.random((3, 4)))
    print(a)
    #把矩阵拉成成向量
    print(a.ravel())
    a.shape = (6,2)
    print(a)
    print("-----------")
    print((a.T))#转置矩阵
    #指定为-1的意思是自动计算行数
    print(a.reshape(3,-1))
    print("---------------")
    #取整操作
    a = numpy.floor(10 * numpy.random.random((2, 2)))
    b = numpy.floor(10 * numpy.random.random((2, 2)))
    #行之间的拼接
    print((numpy.hstack((a, b))))
    #列之间的拼接
    print((numpy.vstack((a, b))))
    print("-----------------")
    a = numpy.floor(10 * numpy.random.random((2, 12)))
    print((numpy.hsplit(a, 3)))#按照行进行切分
    print((numpy.vsplit(a, 2)))#按照列进行切分
math_array()

[20 29 38 47]
[19 28 37 46]
[0 1 4 9]
[ True  True False False]
----------
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[[6. 5. 7. 6.]
 [6. 8. 5. 8.]
 [1. 4. 3. 1.]]
[6. 5. 7. 6. 6. 8. 5. 8. 1. 4. 3. 1.]
[[6. 5.]
 [7. 6.]
 [6. 8.]
 [5. 8.]
 [1. 4.]
 [3. 1.]]
-----------
[[6. 7. 6. 5. 1. 3.]
 [5. 6. 8. 8. 4. 1.]]
[[6. 5. 7. 6.]
 [6. 8. 5. 8.]
 [1. 4. 3. 1.]]
---------------
[[4. 3. 6. 6.]
 [1. 3. 1. 9.]]
[[4. 3.]
 [1. 3.]
 [6. 6.]
 [1. 9.]]
-----------------
[array([[1., 1., 4., 9.],
       [9., 6., 4., 2.]]), array([[4., 0., 0., 9.],
       [4., 4., 2., 1.]]), array([[7., 5., 0., 3.],
       [1., 3., 1., 9.]])]
[array([[1., 1., 4., 9., 4., 0., 0., 9., 7., 5., 0., 3.]]), array([[9., 6., 4., 2., 4., 4., 2., 1., 1., 3., 1., 9.]])]


In [61]:
#矩阵的复制
def copy_arrany():
    #等号复制，形式相同，id相当
    a = numpy.arange(12)
    b = a
    print( (b is a) )
    print((id(a)))
    print((id(b)))
    print("-----------")
    #指向不同，id不同，共用的值是相同的
    c = a.view()#浅复制
    print((c is a))
    c.shape= 2,6
    print(a.shape)
    c[0,4] = 1234
    print(a)
    print(id(a))
    print(id(c))
    print("-------------")
    #指向不同，共用值不同
    d = a.copy()#之后d和a就没有关系，深复制
    d is a
    d[0] = 9999
    print(d)
    print(a)
copy_arrany()

True
2504472330032
2504472330032
-----------
False
(12,)
[   0    1    2    3 1234    5    6    7    8    9   10   11]
2504472330032
2504466042192
-------------
[9999    1    2    3 1234    5    6    7    8    9   10   11]
[   0    1    2    3 1234    5    6    7    8    9   10   11]


In [62]:
#排序与索引问题
def max_suoying():
    data = numpy.sin(numpy.arange(20)).reshape(5, 4)
    print(data)
    ind = data.argmax(axis=0)
    print(ind)
    #输出每列最大的索引
    data_max = data[ind,range(data.shape[1])]
    print(data_max)
    print("-------------")
    a = numpy.arange(0, 40, 10)
    #对a进行扩展
    b = numpy.tile(a, (3, 5))
    print(b)
    print("-----------")
    #排序
    a = numpy.array([[4, 3, 5], [1, 2, 1]])
    b = numpy.sort(a, axis=1)
    print(b)
    a = numpy.array([4, 3, 1, 2])
    #按照索引排序
    j = numpy.argsort(a)
    print(j)
    print(a[j])
max_suoying()

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]
-------------
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]
-----------
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
[1 2 3 4]


## 扩充内容
- NumPy 中定义的最重要的对象是称为 `ndarray` 的 N 维数组类型。 它描述相同类型的元素集合。 可以使用基于零的索引访问集合中的项目。
- 创建

```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

- 参数

<table cellspacing="0" border="1"><thead><tr><td style="background-color:#eff3f5;border-color:#dddddd;">
			<p style="margin-left:0cm;"><strong><span style="color:#4f4f4f;">序号</span></strong></p>
			</td>
			<td style="background-color:#eff3f5;border-color:#dddddd;">
			<p style="margin-left:0cm;"><strong><span style="color:#4f4f4f;">参数及描述</span></strong></p>
			</td>
		</tr></thead><tbody><tr><td style="background-color:#ffffff;border-color:#dddddd;">
			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">1.</span></p>
			</td>
			<td style="background-color:#ffffff;">
			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">object</span></code>&nbsp;<span style="color:#4f4f4f;">任何暴露数组接口方法的对象都会返回一个数组或任何（嵌套）序列。</span></p>
			</td>
		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">2.</span></p>
			</td>
			<td style="background-color:#f7f7f7;">
			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">dtype</span></code>&nbsp;<span style="color:#4f4f4f;">数组的所需数据类型，可选。</span></p>
			</td>
		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">3.</span></p>
			</td>
			<td style="background-color:#ffffff;">
			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">copy</span></code>&nbsp;<span style="color:#4f4f4f;">可选，默认为</span><code><span style="color:#4f4f4f;">true</span></code><span style="color:#4f4f4f;">，对象是否被复制。</span></p>
			</td>
		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">4.</span></p>
			</td>
			<td style="background-color:#f7f7f7;">
			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">order</span></code>&nbsp;<code><span style="color:#4f4f4f;">C</span></code><span style="color:#4f4f4f;">（按行）、</span><code><span style="color:#4f4f4f;">F</span></code><span style="color:#4f4f4f;">（按列）或</span><code><span style="color:#4f4f4f;">A</span></code><span style="color:#4f4f4f;">（任意，默认）。</span></p>
			</td>
		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">5.</span></p>
			</td>
			<td style="background-color:#ffffff;">
			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">subok</span></code>&nbsp;<span style="color:#4f4f4f;">默认情况下，返回的数组被强制为基类数组。 如果为</span><code><span style="color:#4f4f4f;">true</span></code><span style="color:#4f4f4f;">，则返回子类。</span></p>
			</td>
		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">6.</span></p>
			</td>
			<td style="background-color:#f7f7f7;">
			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">ndimin</span></code>&nbsp;<span style="color:#4f4f4f;">指定返回数组的最小维数。</span></p>
			</td>
		</tr></tbody></table>

- #### dtype类型

- <table cellspacing="0" border="1"><thead><tr><td style="background-color:#eff3f5;border-color:#dddddd;">
  			<p style="margin-left:0cm;"><strong><span style="color:#4f4f4f;">序号</span></strong></p>
        			</td>
        			<td style="background-color:#eff3f5;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><strong><span style="color:#4f4f4f;">数据类型及描述</span></strong></p>
        			</td>
        		</tr></thead><tbody><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">1.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">bool_</span></code>&nbsp;<span style="color:#4f4f4f;">存储为一个字节的布尔值（真或假）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">2.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">int_</span></code>&nbsp;<span style="color:#4f4f4f;">默认整数，相当于 C 的</span><code><span style="color:#4f4f4f;">long</span></code><span style="color:#4f4f4f;">，通常为</span><code><span style="color:#4f4f4f;">int32</span></code><span style="color:#4f4f4f;">或</span><code><span style="color:#4f4f4f;">int64</span></code></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">3.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">intc</span></code>&nbsp;<span style="color:#4f4f4f;">相当于 C 的</span><code><span style="color:#4f4f4f;">int</span></code><span style="color:#4f4f4f;">，通常为</span><code><span style="color:#4f4f4f;">int32</span></code><span style="color:#4f4f4f;">或</span><code><span style="color:#4f4f4f;">int64</span></code></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">4.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">intp</span></code>&nbsp;<span style="color:#4f4f4f;">用于索引的整数，相当于 C 的</span><code><span style="color:#4f4f4f;">size_t</span></code><span style="color:#4f4f4f;">，通常为</span><code><span style="color:#4f4f4f;">int32</span></code><span style="color:#4f4f4f;">或</span><code><span style="color:#4f4f4f;">int64</span></code></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">5.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">int8</span></code>&nbsp;<span style="color:#4f4f4f;">字节（-128 ~ 127）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">6.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">int16</span></code><span style="color:#4f4f4f;">&nbsp;16 </span><span style="color:#4f4f4f;">位整数（-32768 ~ 32767）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">7.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">int32</span></code><span style="color:#4f4f4f;">&nbsp;32 </span><span style="color:#4f4f4f;">位整数（-2147483648 ~ 2147483647）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">8.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">int64</span></code><span style="color:#4f4f4f;">&nbsp;64 </span><span style="color:#4f4f4f;">位整数（-9223372036854775808 ~ 9223372036854775807）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">9.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">uint8</span></code><span style="color:#4f4f4f;">&nbsp;8 </span><span style="color:#4f4f4f;">位无符号整数（0 ~ 255）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">10.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">uint16</span></code><span style="color:#4f4f4f;">&nbsp;16 </span><span style="color:#4f4f4f;">位无符号整数（0 ~ 65535）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">11.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">uint32</span></code><span style="color:#4f4f4f;">&nbsp;32 </span><span style="color:#4f4f4f;">位无符号整数（0 ~ 4294967295）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">12.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">uint64</span></code><span style="color:#4f4f4f;">&nbsp;64 </span><span style="color:#4f4f4f;">位无符号整数（0 ~ 18446744073709551615）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">13.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">float_</span></code>&nbsp;<code><span style="color:#4f4f4f;">float64</span></code><span style="color:#4f4f4f;">的简写</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">14.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">float16</span></code>&nbsp;<span style="color:#4f4f4f;">半精度浮点：符号位，5 位指数，10 位尾数</span></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">15.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">float32</span></code>&nbsp;<span style="color:#4f4f4f;">单精度浮点：符号位，8 位指数，23 位尾数</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">16.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">float64</span></code>&nbsp;<span style="color:#4f4f4f;">双精度浮点：符号位，11 位指数，52 位尾数</span></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">17.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">complex_</span></code>&nbsp;<code><span style="color:#4f4f4f;">complex128</span></code><span style="color:#4f4f4f;">的简写</span></p>
        			</td>
        		</tr><tr><td style="background-color:#f7f7f7;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">18.</span></p>
        			</td>
        			<td style="background-color:#f7f7f7;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">complex64</span></code>&nbsp;<span style="color:#4f4f4f;">复数，由两个 32 位浮点表示（实部和虚部）</span></p>
        			</td>
        		</tr><tr><td style="background-color:#ffffff;border-color:#dddddd;">
        			<p style="margin-left:0cm;"><span style="color:#4f4f4f;">19.</span></p>
        			</td>
        			<td style="background-color:#ffffff;">
        			<p style="margin-left:0cm;"><code><span style="color:#4f4f4f;">complex128</span></code>&nbsp;<span style="color:#4f4f4f;">复数，由两个 64 位浮点表示（实部和虚部）</span></p>
        			</td>
        		</tr></tbody></table>

> `dtype`可由一下语法构造：
>
> numpy.dtype(object, align, copy)
>
> - `Object`：被转换为数据类型的对象。
> - `Align`：如果为`true`，则向字段添加间隔，使其类似 C 的结构体。
> - `Copy` ? 生成`dtype`对象的新副本，如果为`flase`，结果是内建数据类型对象的引用。

